# Generated by Django 4.1.3 on 2022-11-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
