# Generated by Django 4.1.3 on 2022-11-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_post_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='map',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.IntegerField(default=54.68),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.IntegerField(default=23.88),
        ),
    ]
