# Generated by Django 4.1.3 on 2022-11-08 19:59

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='54.68, 23.88', max_length=63),
            preserve_default=False,
        ),
    ]
