# Generated by Django 4.1.3 on 2022-11-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
