# Generated by Django 4.1.3 on 2022-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_post_latitude_remove_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='images/img.png', null=True, upload_to='images/'),
        ),
    ]
