# Generated by Django 4.1.3 on 2022-11-10 13:14

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='54.6878,25.2797', max_length=63),
        ),
    ]
