# Generated by Django 4.1.3 on 2022-11-16 12:33

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_post_location2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location2',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
    ]
