# Generated by Django 4.1.3 on 2022-11-16 13:01

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [54.6872, 25.2797], 'marker_color': 'blue'}),
        ),
    ]
