# Generated by Django 4.1.3 on 2022-11-17 08:45

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [25.2797, 54.6872], 'marker_color': 'orange', 'readonly': False, 'style': 'mapbox://styles/mapbox/dark-v10'}),
        ),
    ]
